extends Node

const vc := preload("res://scripts/puzzles/troubleshooter/value_converter.gd").ValueConverter
const RED_LIGHT: StandardMaterial3D = preload("res://assets/materials/red_light.tres")
const BLUE_LIGHT: StandardMaterial3D = preload("res://assets/materials/blue_light.tres")
const GREEN_LIGHT: StandardMaterial3D = preload("res://assets/materials/green_light.tres")

var inputs: Dictionary[String, MachineInput]
var outputs: Dictionary[String, MachineOutput]
var input_to_output: Dictionary[String, String]

@onready var _button: Button = %Button
@onready var _dial: SpinBox = %SpinBox
@onready var _slider: HSlider = %HSlider
@onready var _wave: Sprite3D = %Wave
@onready var _gauge: Node3D = %Gauge
@onready var _color: MeshInstance3D = %Color

var solution: Dictionary[String, float] = {
	"wave": -1.0,
	"gauge": -1.0,
	"color": -1.0,
}

func _ready() -> void:
	inputs = {
		"button": MachineInput.new(
			_button,
			_button.pressed,
			func (_b: Button) -> float: return 0.0,
			func (v: float) -> float: return v
		),
		"dial": MachineInput.new(
			_dial,
			_dial.value_changed,
			func (n: Range) -> float: return n.value,
			func (v: float) -> float: return vc.convert_discrete_to_intermediate(v, [0.0, 1.0]),
		),
		"slider": MachineInput.new(
			_slider,
			_slider.value_changed,
			func (n: Range) -> float: return n.value,
			func (v: float) -> float: return vc.convert_float_to_intermediate(
				v,
				_slider.min_value,
				_slider.max_value
			),
		),
	}
	
	# TODO: Move solutions to be generated by input but checked by output?
	#       Allows multiple solutions?
	# FIXME: Move magic number input limits to constants or object property
	# generate solution input values
	solution["button"] = 0.0
	solution["dial"] = [0.0, 1.0].pick_random()
	solution["slider"] = randf_range(_slider.min_value, _slider.max_value)
	
	outputs = {
		"wave": MachineOutput.new(
			_wave,
			func (w: Sprite3D, v: Variant) -> void: w.frame = v == "wavy",
			func (i: float) -> Variant: return vc.convert_intermediate_to_discrete(
				i,
				["flat", "wavy"]
			)
		),
		"gauge": MachineOutput.new(
			_gauge,
			func (g: Node3D, v: float) -> void: g.scale.x = v,
			func (i: float) -> float: return vc.convert_intermediate_to_float(
				i,
				0.1,
				1.0
			)
		),
		"color": MachineOutput.new(
			_color,
			func (s: MeshInstance3D, v: StandardMaterial3D) -> void:
			s.mesh.surface_set_material(
				0,
				v
			),
			func (i: float) -> Variant: return vc.convert_intermediate_to_discrete(
				i,
				[RED_LIGHT, GREEN_LIGHT, BLUE_LIGHT]
			)
		),
	}
	
	var input_keys: Array = inputs.keys()
	var output_keys: Array = outputs.keys()
	output_keys.shuffle()
	
	for i: int in mini(input_keys.size(), output_keys.size()):
		input_to_output[input_keys[i]] = output_keys[i]
	
	print(input_to_output)

	for i: String in input_to_output:
		var o: String = input_to_output[i]
		inputs[i].signal_triggered.connect(func (..._args: Array) -> void:
			outputs[o].set_from_intermediate(inputs[i].get_as_intermediate())
		)

func is_solved() -> bool:
	for i_name: String in inputs:
		if solution.get(i_name) != inputs[i_name].get_raw():
			return false
		
	return true

class MachineInput:
	var signal_triggered: Signal
	
	var _node: Node
	var _get_value: Callable
	var _get_value_as_intermediate: Callable
	
	func _init(node: Node,
		trigger_signal: Signal,
		value_getter: Callable,
		convert_to_intermediate: Callable
	) -> void:
		signal_triggered = trigger_signal
		_node = node
		_get_value = value_getter
		_get_value_as_intermediate = func () -> float:
			return convert_to_intermediate.call(value_getter.call(_node))
	
	func get_raw() -> Variant:
		return _get_value.call(_node)
	
	func get_as_intermediate() -> float:
		return _get_value_as_intermediate.call()


class MachineOutput:
	var _node: Node
	var _set_value_from_intermediate: Callable
	
	func _init(node: Node, value_setter: Callable, convert_from_intermediate: Callable) -> void:
		_node = node
		_set_value_from_intermediate = func (intermediate: float) -> void:
			value_setter.call(_node, convert_from_intermediate.call(intermediate))
	
	func set_from_intermediate(intermediate_value: float) -> void:
		_set_value_from_intermediate.call(intermediate_value)
